// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Monke.Metrics.Database;

#nullable disable

namespace Monke.Metrics.Migrations
{
    [DbContext(typeof(MetricsDbContext))]
    [Migration("20260717140556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Monke.Metrics.Models.Cpu.CpuCoreHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PercentProcessorTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CpuCoreHistory");
                });

            modelBuilder.Entity("Monke.Metrics.Models.Cpu.CpuHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CurrentClockSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PercentProcessorTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CpuHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
