// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monke.Metrics.Database;

#nullable disable

namespace Monke.Metrics.Migrations
{
    [DbContext(typeof(MetricsDbContext))]
    partial class MetricsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Monke.Metrics.Models.Cpu.CpuCoreHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PercentProcessorTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CpuIndex", "CoreIndex", "Timestamp");

                    b.ToTable("CpuCoreHistory");
                });

            modelBuilder.Entity("Monke.Metrics.Models.Cpu.CpuHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CurrentClockSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PercentProcessorTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CpuIndex", "Timestamp");

                    b.ToTable("CpuHistory");
                });

            modelBuilder.Entity("Monke.Metrics.Models.Drives.VolumeHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("FreeSpace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Timestamp");

                    b.ToTable("VolumeHistory");
                });

            modelBuilder.Entity("Monke.Metrics.Models.Memory.MemoryHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AvailablePageFile")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AvailablePhysical")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AvailableVirtual")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MemoryHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
